import { Outfit } from "next/font/google";
import "./globals.css";

const caveat = Outfit({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  display: "swap",
  variable: "--font-caveat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${caveat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
